id: A9210E3C9
title: 'Great Pangs of Devotion: A Prayer to the Gurus and Three Roots in General
  and Especially the Two Thartsé Khenchen Vajradhara Brothers and Jamyang Khyentse
  Wangpo'
type: translation
pechas:
- IF6B653CB
- I097886E1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:18.436397
  last_modified_at: 2023-01-04 12:35:18.436410
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IF6B653CB/E467: 940E
  I097886E1/C7AB: 940E
